### ISSUE TITLE
Problems with launching app

### ISSUE THREAD

**Issue by kavryn** [sajera/generator-electron-angular#2]
Hi,
First of all, this project requires bower to be installed globally, otherwise installation stops at pre-install (need to add it to package.json).

Also, I selected typescript + less. After that it asked me to select 1 of 10 angularjs (not angular) versions - I selected №3 (v1.6.4) and after that I have 2 errors:

source\scripts\states\layout.controller.js 12:7
error 'root' is assigned a value but never used no-unused-vars
source\scripts\states\home\home.controller.js 10:7
error 'vm' is assigned a value but never used no-unused-vars

? 2problems (2 errors, 0 warnings)

After that Electron UI is opened with errors in console:
Uncaught Error: Cannot find module 'angular'
    at Module._resolveFilename (module.js:470)
    at Function.Module._resolveFilename (F:\Development\electron-angular2\node_modules\electron\dist\resources\electron.asar\common\reset-se…:35)
    at Function.Module._load (module.js:418)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at restangular.js:12
    at restangular.js:17

**Comment by sajera** [comment]
Hello and thank you. I did not reach the release versions a bit.

"pre-install bower" - You're right, it's worth considering. I'll fix it in next version.

"select 1 of 10 angularjs versions" - This error is known to me. Its correction will be in the next version.(bower resolutions)

About the typescript. I'm afraid in the next versions I will temporarily remove the ability to generate a build process on a typescript, since there is a catastrophic lack of time to finalize the build process for it.
